site_name: Leitor PDF

repo_url: https://github.com/Andre-Rafael/leitor_pdf
repo_name: Andre-Rafael/leitor_pdf
edit_uri: tree/main/docs

theme:
  name: readthedocs
  language: pt-BR
  logo: assets/logo_doc_python.jpg
  favicon: assets/logo_doc_python.jpg

markdown_extensions:
  - attr_list

extra_css:
  - stylesheet/extra.css

watch:
  - leitor_pdf

plugins:
- macros
- mkdocstrings:
    handlers:
      python:
        paths: [leitor_pdf]

extra:
  commands:
    run: leitor_pdf